USE [master]
GO
/****** Object:  Database [RentAPlaceFinal]    Script Date: 05-09-2025 12:31:34 ******/
CREATE DATABASE [RentAPlaceFinal]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RentAPlaceFinal', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\RentAPlaceFinal.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'RentAPlaceFinal_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\RentAPlaceFinal_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [RentAPlaceFinal] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RentAPlaceFinal].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [RentAPlaceFinal] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [RentAPlaceFinal] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [RentAPlaceFinal] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [RentAPlaceFinal] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [RentAPlaceFinal] SET ARITHABORT OFF 
GO
ALTER DATABASE [RentAPlaceFinal] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [RentAPlaceFinal] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [RentAPlaceFinal] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [RentAPlaceFinal] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [RentAPlaceFinal] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [RentAPlaceFinal] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [RentAPlaceFinal] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [RentAPlaceFinal] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [RentAPlaceFinal] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [RentAPlaceFinal] SET  DISABLE_BROKER 
GO
ALTER DATABASE [RentAPlaceFinal] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [RentAPlaceFinal] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [RentAPlaceFinal] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [RentAPlaceFinal] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [RentAPlaceFinal] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [RentAPlaceFinal] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [RentAPlaceFinal] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [RentAPlaceFinal] SET RECOVERY FULL 
GO
ALTER DATABASE [RentAPlaceFinal] SET  MULTI_USER 
GO
ALTER DATABASE [RentAPlaceFinal] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [RentAPlaceFinal] SET DB_CHAINING OFF 
GO
ALTER DATABASE [RentAPlaceFinal] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [RentAPlaceFinal] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [RentAPlaceFinal] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [RentAPlaceFinal] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'RentAPlaceFinal', N'ON'
GO
ALTER DATABASE [RentAPlaceFinal] SET QUERY_STORE = ON
GO
ALTER DATABASE [RentAPlaceFinal] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [RentAPlaceFinal]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 05-09-2025 12:31:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Messages]    Script Date: 05-09-2025 12:31:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Messages](
	[MessageId] [int] IDENTITY(1,1) NOT NULL,
	[FromUserId] [int] NOT NULL,
	[ToUserId] [int] NOT NULL,
	[PropertyId] [int] NOT NULL,
	[Content] [nvarchar](max) NOT NULL,
	[SentAt] [datetime2](7) NOT NULL,
	[CreatedAt] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_Messages] PRIMARY KEY CLUSTERED 
(
	[MessageId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Properties]    Script Date: 05-09-2025 12:31:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Properties](
	[PropertyId] [int] IDENTITY(1,1) NOT NULL,
	[OwnerId] [int] NOT NULL,
	[Title] [nvarchar](max) NOT NULL,
	[Description] [nvarchar](max) NOT NULL,
	[Type] [nvarchar](max) NOT NULL,
	[Location] [nvarchar](max) NOT NULL,
	[Features] [nvarchar](max) NULL,
	[PricePerNight] [decimal](10, 2) NOT NULL,
	[Rating] [float] NOT NULL,
	[Images] [nvarchar](max) NULL,
	[CreatedAt] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_Properties] PRIMARY KEY CLUSTERED 
(
	[PropertyId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Reservations]    Script Date: 05-09-2025 12:31:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Reservations](
	[ReservationId] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [int] NOT NULL,
	[PropertyId] [int] NOT NULL,
	[CheckIn] [datetime2](7) NOT NULL,
	[CheckOut] [datetime2](7) NOT NULL,
	[Status] [nvarchar](max) NOT NULL,
	[CreatedAt] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_Reservations] PRIMARY KEY CLUSTERED 
(
	[ReservationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 05-09-2025 12:31:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[UserId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](max) NOT NULL,
	[Email] [nvarchar](max) NOT NULL,
	[PasswordHash] [nvarchar](max) NOT NULL,
	[Role] [nvarchar](max) NOT NULL,
	[CreatedAt] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Index [IX_Messages_FromUserId]    Script Date: 05-09-2025 12:31:34 ******/
CREATE NONCLUSTERED INDEX [IX_Messages_FromUserId] ON [dbo].[Messages]
(
	[FromUserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Messages_PropertyId]    Script Date: 05-09-2025 12:31:34 ******/
CREATE NONCLUSTERED INDEX [IX_Messages_PropertyId] ON [dbo].[Messages]
(
	[PropertyId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Messages_ToUserId]    Script Date: 05-09-2025 12:31:34 ******/
CREATE NONCLUSTERED INDEX [IX_Messages_ToUserId] ON [dbo].[Messages]
(
	[ToUserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Properties_OwnerId]    Script Date: 05-09-2025 12:31:34 ******/
CREATE NONCLUSTERED INDEX [IX_Properties_OwnerId] ON [dbo].[Properties]
(
	[OwnerId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Reservations_PropertyId]    Script Date: 05-09-2025 12:31:34 ******/
CREATE NONCLUSTERED INDEX [IX_Reservations_PropertyId] ON [dbo].[Reservations]
(
	[PropertyId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Reservations_UserId]    Script Date: 05-09-2025 12:31:34 ******/
CREATE NONCLUSTERED INDEX [IX_Reservations_UserId] ON [dbo].[Reservations]
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Messages]  WITH CHECK ADD  CONSTRAINT [FK_Messages_Properties_PropertyId] FOREIGN KEY([PropertyId])
REFERENCES [dbo].[Properties] ([PropertyId])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Messages] CHECK CONSTRAINT [FK_Messages_Properties_PropertyId]
GO
ALTER TABLE [dbo].[Messages]  WITH CHECK ADD  CONSTRAINT [FK_Messages_Users_FromUserId] FOREIGN KEY([FromUserId])
REFERENCES [dbo].[Users] ([UserId])
GO
ALTER TABLE [dbo].[Messages] CHECK CONSTRAINT [FK_Messages_Users_FromUserId]
GO
ALTER TABLE [dbo].[Messages]  WITH CHECK ADD  CONSTRAINT [FK_Messages_Users_ToUserId] FOREIGN KEY([ToUserId])
REFERENCES [dbo].[Users] ([UserId])
GO
ALTER TABLE [dbo].[Messages] CHECK CONSTRAINT [FK_Messages_Users_ToUserId]
GO
ALTER TABLE [dbo].[Properties]  WITH CHECK ADD  CONSTRAINT [FK_Properties_Users_OwnerId] FOREIGN KEY([OwnerId])
REFERENCES [dbo].[Users] ([UserId])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Properties] CHECK CONSTRAINT [FK_Properties_Users_OwnerId]
GO
ALTER TABLE [dbo].[Reservations]  WITH CHECK ADD  CONSTRAINT [FK_Reservations_Properties_PropertyId] FOREIGN KEY([PropertyId])
REFERENCES [dbo].[Properties] ([PropertyId])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Reservations] CHECK CONSTRAINT [FK_Reservations_Properties_PropertyId]
GO
ALTER TABLE [dbo].[Reservations]  WITH CHECK ADD  CONSTRAINT [FK_Reservations_Users_UserId] FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([UserId])
GO
ALTER TABLE [dbo].[Reservations] CHECK CONSTRAINT [FK_Reservations_Users_UserId]
GO
USE [master]
GO
ALTER DATABASE [RentAPlaceFinal] SET  READ_WRITE 
GO
